name: Deploy latest backend

on:
  push:
    branches:
      - rewrite
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install and configure Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      #folder root must have procfile
      #https://www.koyeb.com/docs/build-and-deploy/build-from-git#execution-run-command-and-the-procfile
      - name: Deploy to existing service via Koyeb CLI
        working-directory: ./js_serverless
        run: |
          koyeb deploy . ${{ secrets.KOYEB_APP_NAME }}/${{ secrets.KOYEB_SERVICE_NAME }}
