name: Code unit test

on:
  push:
    branches:
      - rewrite
  pull_request:
    branches:
      - rewrite
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Install dependencies
        run: cd js_serverless && npm ci

      - name: Run tests
        run: cd js_serverless && npm test
